name: PR Handling

#################
# NOTE: We are using pull_request_target here:
#       https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
#       
#       So, only API calls should be made in the actions defined here. The
#       committed code should _NOT_ be touched in any case.
#################

on:
  pull_request_target:
    types: [ opened, reopened ]
    
jobs:
  assign-pr:
    name: Assign PR to author
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.1
 
